//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brod()
        {
            this.Kapetan = new HashSet<Kapetan>();
            this.Posada = new HashSet<Posada>();
            this.Poseduje = new HashSet<Poseduje>();
        }
    
        public System.Guid IDBroda { get; set; }
        public string Ime { get; set; }
        public System.DateTime GodGrad { get; set; }
        public Nullable<int> MaxBrzina { get; set; }
        public Nullable<int> Duzina { get; set; }
        public Nullable<int> Sirina { get; set; }
        public System.Guid IDBrodog { get; set; }
    
        public virtual Brodogradiliste Brodogradiliste { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kapetan> Kapetan { get; set; }
        public virtual Kruzer Kruzer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Posada> Posada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Poseduje> Poseduje { get; set; }
        public virtual Tanker Tanker { get; set; }
        public virtual Teretni_Brod Teretni_Brod { get; set; }
    }
}
