//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brodogradiliste
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brodogradiliste()
        {
            this.Brod = new HashSet<Brod>();
            this.Poseduje = new HashSet<Poseduje>();
        }
    
        public System.Guid IDBrodog { get; set; }
        public string Naziv { get; set; }
        public string Lokacija { get; set; }
        public Nullable<int> BrNaprBrod { get; set; }
        public Nullable<int> BrPrist { get; set; }
        public Nullable<bool> PosedSuvDok { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Brod> Brod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Poseduje> Poseduje { get; set; }
    }
}
