//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mornar
    {
        public string JMBG { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Pol { get; set; }
        public string Rank { get; set; }
        public Nullable<System.Guid> ID { get; set; }
        public Nullable<System.Guid> IDBroda { get; set; }
    
        public virtual Posada Posada { get; set; }
        public virtual Teretni_Brod Teretni_Brod { get; set; }
    }
}
