//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Posada()
        {
            this.Mornar = new HashSet<Mornar>();
        }
    
        public System.Guid ID { get; set; }
        public string Ime { get; set; }
        public Nullable<int> Kapacitet { get; set; }
        public string JMBG_Kormilar { get; set; }
        public string JMBG_Kapetan { get; set; }
        public System.Guid IDBroda { get; set; }
    
        public virtual Brod Brod { get; set; }
        public virtual Kapetan Kapetan { get; set; }
        public virtual Kormilar Kormilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mornar> Mornar { get; set; }
    }
}
