//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tanker
    {
        public System.Guid IDBroda { get; set; }
        public Nullable<int> Nosivost { get; set; }
        public string TipTeret { get; set; }
    
        public virtual Brod Brod { get; set; }
    }
}
